# Generated by Django 5.1.6 on 2025-03-24 21:44

import dashboard.models
import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage(credentials=None), upload_to=dashboard.models.upload_to_gcs),
        ),
    ]
