# Generated by Django 5.1.6 on 2025-04-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='chat_messages', to='dashboard.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('assignments', 'Assignments'), ('class_notes', 'Class Notes'), ('syllabus', 'Syllabus'), ('chatbot_files', 'Chatbot Files')], max_length=50),
        ),
    ]
